# Generated by Django 5.1.7 on 2025-03-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rib',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
