# Generated by Django 5.1.7 on 2025-03-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_rib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rib',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
