# Generated by Django 5.1.7 on 2025-03-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('delivery_street', models.CharField(max_length=255)),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_location', models.CharField(blank=True, help_text='Google Maps location string', max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Driver Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('no_answer', 'No Answer'), ('postponed', 'Postponed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
