# Generated by Django 5.1.7 on 2025-03-13 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='mainapp_ord_status_86699a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='mainapp_ord_created_9463e2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller'], name='mainapp_ord_seller__0ee320_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['driver'], name='mainapp_ord_driver__d7608b_idx'),
        ),
    ]
