# Generated by Django 5.1.7 on 2025-03-24 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-updated_at'], name='mainapp_ord_updated_4f5cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['seller'], name='mainapp_sto_seller__eb44cd_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['approved'], name='mainapp_sto_approve_af2ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['updated_at'], name='mainapp_sto_updated_003687_idx'),
        ),
    ]
